---
# tasks file for dns-slaves
- name: install packages
  yum:
    name: ['bind', 'bind-utils']
    state: latest
 
- name: start named
  service:
    name: named
    enabled: yes
    state: started

- name: configure dns-slave1
  template:
    src: dns.slave1.j2
    dest: /etc/named.conf
  when: ansible_hostname != "prdx-nsw102"

- name: configure dns-slave2
  template:
    src: dns.slave2.j2
    dest: /etc/named.conf
  when: ansible_hostname != "prdx-nsw101"

- name: pull zones from master
  shell:
    cmd: rndc reload ziyotek1.local; rndc reload 35.168.192.in-addr.arpa

- name: restart named
  service: 
    name: named
    enabled: yes
    state: restarted
