---
# tasks file for webservers7

- name: install httpd
  yum: 
    name: httpd
    state: latest

- name: start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: true

- name: create target directory
  file: 
    path: "/var/www/vhosts/{{ ansible_hostname }}/"
    state: directory 
    mode: 0755

- name: deliver html content
  template:
    src: index.j2
    dest: "/var/www/vhosts/{{ ansible_hostname }}/index.html"
    owner: root
    group: root
    mode: 0644

- name: update /etc/hosts file to include load balancer
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: template vhost file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

