---
# tasks file for dns-master
  
- name: install packages
  yum:
    name: ['bind', 'bind-utils']
    state: latest

- name: start named
  service:
    name: named
    state: started

- name: configure dns-master
  template:
    src: dns.master.j2
    dest: /etc/named.conf

- name: copying FLZ file
  template:
    src: ziyotek1.flz.j2
    dest: /var/named/ziyotek1.flz

- name: copying RLZ file
  template:
    src: ziyotek1.rlz.j2
    dest: /var/named/ziyotek1.rlz

- name: start named
  service:
    name: named
    enabled: yes
    state: restarted

