---
# tasks file for common

 
# Setup FTP/Mirror client 

- name: FTP/MIRROR | setup ftp
  yum:
    name: ftp
    state: latest
  when: ansible_hostname != "prdx-ftp101"

- name: FTP/MIRROR | Remove existing repo files
  shell: sudo rm -rf /etc/yum.repos.d/*.repo
  args:
    warn: false
  when: ansible_hostname != "prdx-ftp101"

- name: FTP/MIRROR | Remove existing repo files
  file:
    path: /etc/yum.repos.d/*.repo
    state: absent
  when: ansible_hostname != "prdx-ftp101"

- name: FTP/MIRROR | Use custom repo
  copy:
    src: local.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname != "prdx-ftp101"

- name: FTP/MIRROR | yum clean all
  command: yum clean all
  args:
    warn: no
  when: ansible_hostname != "prdx-ftp101"


#Setup common packages

- name: COMMON | setup common packages
  yum:
    name: ['bind-utils','man','man-pages','mlocate','sysstat','vim']
    state: latest


#Setup NTP client

- name: NTP | instal packages
  yum:
    name: chrony
    state: latest
  when: ansible_hostname != "prdx-ntp101"
  when: ansible_hostname != "prdx-ntp102"

- name: NTP | setup chrony
  copy:
    src: chrony.conf
    dest: /etc/chrony.conf
  when: ansible_hostname != "prdx-ntp101"
  when: ansible_hostname != "prdx-ntp102"

- name: NTP | restart chronyd
  service:
    name: chronyd
    state: restarted
  when: ansible_hostname != "prdx-ntp101"
  when: ansible_hostname != "prdx-ntp102"


#Setup NFS-AutoFS clients

- name: NFS | instal packages
  yum:
    name: ['nfs-utils','autofs']
    state: latest
  when: ansible_hostname != "prdx-nfs101"

- name: NFS | create a mountpoint for NFS
  file:
    path: /share
    state: directory
    mode: 755
    owner: nfsnobody
    group: nfsnobody
 when: ansible_hostname != "prdx-nfs101"

- name: AUTOFS | Create auto.master and add map-files
  template:
    src: auto.master.j2
    dest: /etc/auto.master
  when: ansible_hostname != "prdx-nfs101"

- name: AUTOFS | Create map-files for /share
  template:
    src: auto.demo.j2
    dest: /etc/auto.demo
  when: ansible_hostname != "prdx-nfs101"

- name: AUTOFS | Create map-files for /home
  template:
    src: auto.home.j2
    dest: /etc/auto.home
  when: ansible_hostname != "prdx-nfs101"

- name: AUTOFS | Enable Autofs 
  service:
    name: autofs
    state: restarted
    enabled: yes
  when: ansible_hostname != "prdx-nfs101"


#Setup LDAP client

- name: LDAP | instal packages
  yum:
    name: ['openldap-clients','nss-pam-ldapd','authconfig']
    state: latest
  when: ansible_hostname != "prdx-ldap101"

- name: LDAP | setup ldap cert
  command: wget http://192.168.35.32/ca-bundle.crt 

- name: LDAP | configure authconfig
  command: authconfig --enableldap --enableldapauth --ldapserver=192.168.35.32 --ldapbasedn="dc=ziyotek1,dc=local" --enableldaptls --ldaploadcacert=http://192.168.35.32/ca-bundle.crt --enablemkhomedir --update
  when: ansible_hostname != "prdx-ldap101"

- name: LDAP | restart service
  service:
    name: ######## 
    state: restarted
    enabled: yes
  when: ansible_hostname != "prdx-ldap101"

#Setup Samba clients

- name: SAMBA | install packages
  yum:
    name: ['samba-client', 'cifs-utils']
    state: latest
  when: ansible_hostname != "prdx-samba101"

- name: SAMBA | create directory /clients give permissions
  file:
    path: /client
    state: directory
    mode: '777'
  when: ansible_hostname != "prdx-samba101"

- name: SAMBA | append /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: //prdx-samba101/secure /client/ cifs user=sambaadmin,password=password,sec=ntlmssp 0 0
  when: ansible_hostname != "prdx-samba101"

- name: SAMBA | mount a samba share
  shell: mount -a
  args:
    warn: false
  when: ansible_hostname != "prdx-samba101"
